volumes:
  persistent-vol:
    name: ${PERSISTENT_VOL_NAME}
    driver: ${PRO_VOL_DRIVER:-cloudstor:aws}
    driver_opts:
      backing: shared

configs:
  redirect-redmic-config:
    name: ${REDIRECT_REDMIC_CONFIG_NAME}
    file: ./config/conf.d/pro-redirect-redmic.conf
