volumes:
  persistent-vol:
    driver: ${DEV_VOL_DRIVER:-local}
    driver_opts:
      type: ${VOL_TYPE:-nfs}
      o: addr=${VOL_ADDR:-127.0.0.1},vers=${VOL_VERS:-4.2},${VOL_OPTS:-soft,nolock,noacl,noatime,nodiratime}
      device: :${VOL_DEVICE_PREFIX}${PERSISTENT_VOL_DEVICE:-/dhparams-vol/}

configs:
  nginx-proxy-https-redirect-redmic-config:
    file: ./config/conf.d/dev-redirect-redmic.conf
