volumes:
  persistent-vol:
    name: ${PERSISTENT_VOL_NAME:-dhparams-vol}
    driver: ${PRO_VOL_DRIVER:-cloudstor:aws}
    driver_opts:
      backing: shared

configs:
  nginx-proxy-https-redirect-redmic-config:
    file: ./config/conf.d/pro-redirect-redmic.conf
