services:
  nginx-proxy-https:
    deploy:
      placement:
        constraints:
          - engine.labels.availability_zone == ${AWS_REGION}a

configs:
  redirect-redmic-config:
    name: ${REDIRECT_REDMIC_CONFIG_NAME}
    file: ./config/conf.d/pro-redirect-redmic.conf
