services:
  nginx-proxy-https:
    deploy:
      placement:
        constraints:
          - node.labels.${PLACEMENT_CONSTRAINTS_NODE_LABELS_NAME:-gateway} == ${PLACEMENT_CONSTRAINTS_NODE_LABELS_VALUE:-true}

configs:
  redirect-redmic-config:
    name: ${REDIRECT_REDMIC_CONFIG_NAME}
    file: ./config/conf.d/dev-redirect-redmic.conf
