services:
  nginx-proxy-https:
    image: ${IMAGE_NAME:-nginx}:${IMAGE_TAG:-alpine}
    networks:
      traefik-net:
    ports:
      - target: ${HTTPS_INTERNAL_PORT:-443}
        published: ${HTTPS_PORT:-443}
        mode: ${PORT_MODE:-host}
    volumes:
      - persistent-vol:/var/nginx/persistent
      - accesslog-vol:/var/log/nginx/access
    configs:
      - source: nginx-proxy-https-default-config
        target: /etc/nginx/conf.d/default.conf
      - source: nginx-proxy-https-gzip-config
        target: /etc/nginx/conf.d/gzip.conf
      - source: nginx-proxy-https-ssl-params-config
        target: /etc/nginx/conf.d/ssl-params.conf
      - source: nginx-proxy-https-ssl-certs-config
        target: /etc/nginx/conf.d/ssl-certs.conf
      - source: nginx-proxy-https-redirect-redmic-config
        target: /etc/nginx/conf.d/redirect-redmic.conf
      - source: nginx-proxy-https-redirect-ecomarcan-config
        target: /etc/nginx/conf.d/redirect-ecomarcan.conf
      - source: nginx-proxy-https-access-log-config
        target: /etc/nginx/conf.d/00-access-log.conf
    secrets:
      - source: cert-chain-secret
        target: /etc/nginx/certs/chain.pem
      - source: cert-fullchain-secret
        target: /etc/nginx/certs/fullchain.pem
      - source: cert-privkey-secret
        target: /etc/nginx/certs/privkey.pem
    healthcheck:
      test: wget --spider -q http://localhost/nginx-health
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      placement:
        constraints:
          - ${PLACEMENT_CONSTRAINT_NODE_LABEL:-node.labels.gateway==true}
      restart_policy:
        delay: ${RESTART_DELAY:-0s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  accesslog-vol:
    driver: ${VOL_DRIVER:-local}

configs:
  nginx-proxy-https-default-config:
    file: ./config/conf.d/default.conf

  nginx-proxy-https-gzip-config:
    file: ./config/conf.d/gzip.conf

  nginx-proxy-https-ssl-params-config:
    file: ./config/conf.d/ssl-params.conf

  nginx-proxy-https-ssl-certs-config:
    file: ./config/conf.d/ssl-certs.conf

  nginx-proxy-https-redirect-ecomarcan-config:
    file: ./config/conf.d/redirect-ecomarcan.conf

  nginx-proxy-https-access-log-config:
    file: ./config/conf.d/00-access-log.conf

secrets:
  cert-chain-secret:
    name: ${CERT_CHAIN_SECRET_NAME:-cert-chain}
    external: true

  cert-fullchain-secret:
    name: ${CERT_FULLCHAIN_SECRET_NAME:-cert-fullchain}
    external: true

  cert-privkey-secret:
    name: ${CERT_PRIVKEY_SECRET_NAME:-cert-privkey}
    external: true
