version: '3.5'

services:
  nginx-proxy:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - PERSISTENT_PATH
    networks:
      - traefik-net
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - persistent-vol:${PERSISTENT_PATH}
      - cache-vol:/var/nginx/cache
      - acme-vol:/var/www/html
    configs:
      - source: blockips
        target: /etc/nginx/conf.d/blockips.conf
      - source: blacklist
        target: /etc/nginx/conf.d/blacklist.conf
    secrets:
      - source: cert-chain
        target: /etc/nginx/certs/chain.pem
      - source: cert-fullchain
        target: /etc/nginx/certs/fullchain.pem
      - source: cert-privkey
        target: /etc/nginx/certs/privkey.pem
    healthcheck:
      test: wget --spider -S -t 3 http://${PUBLIC_HOSTNAME:-localhost} || (count=$$(ps aux | grep openssl | wc -l); [ $${count} -gt 1 ])
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '2'
          memory: 128M
        reservations:
          memory: 103M

networks:
  traefik-net:
    external: true

volumes:
  cache-vol:
    name: nginx-cache-vol

  persistent-vol:
    name: nginx-persistent-vol

  acme-vol:
    name: acme-vol

configs:
  blockips:
    file: ./config/blockips.conf

secrets:
  cert-chain:
    external: true

  cert-fullchain:
    external: true

  cert-privkey:
    external: true
