version: '3.6'

services:
  nginx-proxy-https:
    deploy:
      placement:
        constraints:
          - node.labels.${PLACEMENT_CONSTRAINTS_NODE_LABELS_NAME:-gateway} == ${PLACEMENT_CONSTRAINTS_NODE_LABELS_VALUE:-true}

configs:
  blacklist-config:
    name: ${BLACKLIST_CONFIG_NAME}
    file: ./config/conf.d/dev-blacklist.conf
