version: '3.5'

services:
  nginx-proxy-https:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/gateway/nginx-proxy-https}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        NGINX_IMAGE_TAG:
        OPENSSL_VERSION:
    environment:
      PERSISTENT_PATH:
    networks:
      traefik-net:
    ports:
      - target: ${HTTPS_INTERNAL_PORT}
        published: ${HTTPS_PORT}
        mode: ${PORT_MODE}
    volumes:
      - persistent-vol:${PERSISTENT_PATH}
      - cache-vol:/var/nginx/cache
    configs:
      - source: blockips-config
        target: /etc/nginx/conf.d/blockips.conf
      - source: blacklist-config
        target: /etc/nginx/conf.d/blacklist.conf
    secrets:
      - source: cert-chain-secret
        target: /etc/nginx/certs/chain.pem
      - source: cert-fullchain-secret
        target: /etc/nginx/certs/fullchain.pem
      - source: cert-privkey-secret
        target: /etc/nginx/certs/privkey.pem
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: ${RESTART_DELAY:-0s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-2}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  cache-vol:
    name: ${CACHE_VOL_NAME:-nginx-cache-vol}

  persistent-vol:
    name: ${PERSISTENT_VOL_NAME:-nginx-persistent-vol}

configs:
  blockips-config:
    name: ${BLOCKIPS_CONFIG_NAME:-nginx-blockips}
    file: ./config/blockips.conf

secrets:
  cert-chain-secret:
    name: ${CERT_CHAIN_SECRET_NAME:-cert-chain}
    external: true

  cert-fullchain-secret:
    name: ${CERT_FULLCHAIN_SECRET_NAME:-cert-fullchain}
    external: true

  cert-privkey-secret:
    name: ${CERT_PRIVKEY_SECRET_NAME:-cert-privkey}
    external: true
