version: '3.5'

services:
  nginx-proxy:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    networks:
      - traefik-net
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - acme-vol:/var/www/html
    secrets:
      - source: cert-chain
        target: /etc/nginx/certs/chain.pem
      - source: cert-fullchain
        target: /etc/nginx/certs/fullchain.pem
      - source: cert-privkey
        target: /etc/nginx/certs/privkey.pem
      - source: cert-dhparam
        target: /etc/nginx/certs/dhparam.pem
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '4'
          memory: 128M
        reservations:
          memory: 103M

networks:
  traefik-net:
    external: true

volumes:
  acme-vol:
    name: acme-vol

secrets:
  cert-chain:
    external: true

  cert-fullchain:
    external: true

  cert-privkey:
    external: true

  cert-dhparam:
    external: true
