log_format access_json escape=json
'{'
'"timestamp":"$time_iso8601",'
'"remote_addr":"$remote_addr",'
'"real_ip":"$realip_remote_addr",'
'"x_forwarded_for":"$http_x_forwarded_for",'
'"remote_user":"$remote_user",'

'"host":"$host",'
'"server_name":"$server_name",'
'"scheme":"$scheme",'

'"method":"$request_method",'
'"request_uri":"$request_uri",'
'"uri":"$uri",'
'"query_string":"$args",'

'"status":$status,'
'"request_length":$request_length,'
'"body_bytes_sent":$body_bytes_sent,'
'"bytes_sent":$bytes_sent,'

'"request_time":$request_time,'
'"upstream_response_time":"$upstream_response_time",'
'"upstream_connect_time":"$upstream_connect_time",'
'"upstream_header_time":"$upstream_header_time",'

'"upstream_addr":"$upstream_addr",'
'"upstream_status":"$upstream_status",'

'"referer":"$http_referer",'
'"user_agent":"$http_user_agent",'

'"content_type":"$sent_http_content_type",'
'"request_id":"$request_id"'
'}';
